# Generated by Django 3.1.7 on 2021-04-02 13:33

from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News_Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Sub_Heading', models.CharField(max_length=100)),
                ('Content', models.TextField()),
                ('Content_Image', models.ImageField(blank=True, null=True, upload_to=web.models.News_Feed.upload_dir)),
                ('Author', models.CharField(max_length=100)),
                ('DateOfPublish', models.DateTimeField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(default='', max_length=50)),
                ('confim_password', models.CharField(default='', max_length=50)),
                ('DOB', models.DateField(max_length=8)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=web.models.Registration.upload_dir)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.CharField(max_length=100)),
                ('created_at', models.TimeField(auto_now=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='web.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='web.user')),
            ],
        ),
    ]
